---
- name: Register a Change
  hosts: nodes
  become: false

  tasks:
    - name: Copy test-{node-id}.json to node
      copy:
        src: files/test-{{ node_id }}.json
        dest: "{{ app_dir }}/test-{{ node_id }}.json"
        mode: '0644'
      register: config

    - name: Display application status
      debug:
        msg: 
          - "Configuration updated: {{ config.changed }}"
